image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build and test:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=televeda-livestream --api-key=$HEROKU_API_KEY
 