image: node:latest
stages:
- deploy
deploy:
type: deploy
stage: deploy
image: ruby:latest
tags:
    - grad
script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY # security add the heroku api to CI/CD setting