image: node:8.10.0

before_script:
  - npm i -g npm@6.13.7

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build and test:
  stage: build
  script:
    - npm install
  tags:
    - grad
  artifacts:
    paths:
      - node_modules/
  
deploy:
  stage: deploy
  image: ruby:latest
  tags:
    - grad
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
 